# server port
server:
  port: 8888

# database
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/pratice_board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: 0000

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml